version: "3.8"
services:
  front:
    build:
      target: dev
    volumes:
      - ./front/src:/app/src
      - ./front/public:/app/public

  back:
    build:
      target: dev
    volumes:
      - ./back:/build

  db:
    image: postgres:16.1
    restart: always
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=airneis
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=airneis
